export const menuItems = [
  { name: "All", href: "#" },
  { name: "Amazon miniTV", href: "#" },
  { name: "Sell", href: "#" },
  { name: "Best Sellers", href: "#" },
  { name: "Mobiles", href: "#" },
  { name: "Today's Deals", href: "#" },
  { name: "Electronics", href: "#" },
  { name: "Customer Service", href: "#" },
  { name: "Prime", href: "#" },
  { name: "New Releases", href: "#" },
  { name: "Home & Kitchen", href: "#" },
  { name: "Gift Ideas", href: "#" },
  { name: "Amazon Pay", href: "#" },
  { name: "Fashion", href: "#" },
  { name: "Computers", href: "#" },
  { name: "Books", href: "#" },
];
